version: "3.8"

services:
  postgres:
    image: postgres:14.2-alpine
    env_file:
      - .env
    volumes:
      - todo_db:/var/lib/postgresql/data
    command: postgres -c 'max_prepared_transactions=0' -c 'fsync=off'
    restart: always
  web:
    build: .
    volumes:
      - .:/rails-app:delegated
    command: bash -c "bin/rails db:create db:migrate && bin/rails s -p 3000 -b '0.0.0.0' && bin/rails tailwindcss:watch"
    restart: always
    ports:
      - "3000:3000"
    links:
      - postgres
    env_file:
      - .env

    depends_on:
      - postgres

volumes:
  todo_db:
